apps/github/.eslintrc.js, apps/github/.gitignore, apps/github/README.md, apps/github/app/layout.tsx, apps/github/app/page.tsx, apps/github/next-env.d.ts, apps/github/next.config.js, apps/github/package.json, apps/github/tsconfig.json, package-lock.json
=> chore(github): init app

.prettierrc.json, packages/eslint-config-custom/library.js, packages/eslint-config-custom/next.js, packages/eslint-config-custom/react-internal.js
- add prettier config
- disable eslint explicit returns rule
=> chore: configure coding tools

apps/github/env.ts, apps/github/msw/elbaRequestHandlers.ts, apps/github/msw/setupTestServer.ts, apps/github/package.json, apps/github/repositories/elba/Error.ts, apps/github/repositories/elba/RequestSender.ts, apps/github/repositories/elba/elba.repository.test.ts, apps/github/repositories/elba/elba.repository.ts, apps/github/repositories/elba/resources/ElbaResource.ts, apps/github/repositories/elba/resources/third-party-apps/ThirdPartyApps.ts, apps/github/repositories/elba/resources/third-party-apps/types.ts, apps/github/repositories/elba/resources/users/Users.ts, apps/github/repositories/elba/resources/users/types.ts, apps/github/vitest.config.ts, package-lock.json
- add env variables + env.ts
- configure vitest
- add msw elba request handlers
- add elba repository
=> feat(github): add elba repository

apps/github/database/client.ts, apps/github/database/index.ts, apps/github/database/schema.ts, apps/github/docker-compose.yml, apps/github/drizzle/0000_omniscient_thena.sql, apps/github/drizzle/meta/0000_snapshot.json, apps/github/drizzle/meta/_journal.json, apps/github/env.ts, apps/github/package.json, apps/github/scripts/migrate.js, package-lock.json
- add drizzle schema
- add database migrate script
- add docker-compose.yml to start a postgres locally
=> chore(github): add local docker postgres

apps/github/app/layout.tsx, apps/github/app/page.tsx, apps/github/app/setup/layout.tsx, apps/github/app/setup/page.tsx, apps/github/package.json, apps/github/repositories/github/client.ts, apps/github/repositories/github/installation.repository.test.ts, apps/github/repositories/github/installation.repository.ts, apps/github/repositories/integration/installation.repository.ts, apps/github/repositories/integration/syncJob.repository.ts, apps/github/services/registerInstallation.service.ts, apps/github/vitest.config.ts, package-lock.json, packages/tsconfig/base.json
- add link that redirect user to the github elba app installation page
- add `/setup` page (redirect from github) that call registerInstallation service
- add integration installation repository
- implement a function that insert installation in db
- add github installation repository
- implement a function that retrieve installation from github
- add registerInstallation service
=> feat(github): add github registration flow

apps/github/app/api/cron/run-users-sync-jobs/route.ts, apps/github/app/setup/layout.tsx, apps/github/app/setup/page.tsx, apps/github/database/schema.ts, apps/github/drizzle/0000_round_nemesis.sql, apps/github/drizzle/meta/0000_snapshot.json, apps/github/drizzle/meta/_journal.json, apps/github/env.ts, apps/github/middleware.ts, apps/github/repositories/github/organization.repository.test.ts, apps/github/repositories/github/organization.repository.ts, apps/github/repositories/integration/installation.repository.ts, apps/github/repositories/integration/installationAdmin.repository.ts, apps/github/repositories/integration/syncJob.repository.ts, apps/github/services/common/formatElbaUser.ts, apps/github/services/common/runSyncJobs.ts, apps/github/services/runUsersSyncJobs.service.ts, apps/github/vercel.json, apps/github/vitest.config.ts
- add next middleware to protect cron endpoint
- update integration syncJob repository
- update integration installation repository
- add integration installationAdmin repository
- add github organization repository
- add runUsersSyncJobs service
- add route `/api/cron/run-users-sync-jobs`
=> feat(github): add run-users-sync-jobs cron

apps/github/app/api/cron/schedule-users-sync-jobs/route.ts, apps/github/env.ts, apps/github/repositories/integration/installation.repository.ts, apps/github/repositories/integration/syncJob.repository.ts, apps/github/services/scheduleSyncJobs.service.ts, apps/github/vercel.json, apps/github/vitest.config.ts
- update integration installation repository
- update integration syncJob repository
- add scheduleUsersSyncJobs service
- add route /api/cron/schedule-users-sync-jobs
=> feat(github): add schedule-users-sync-jobs cron

CONTRIBUTING.MD
=> docs: add contributing.md

.github/PULL_REQUEST_TEMPLATE.md
- add github PULL_REQUEST_TEMPLATE.md
Checklist does not contains about documentation for now. It could be suitable to have a documentation markdown file in the template in order to let every integrator describe how the implementation works.
=> docs: add github PULL_REQUEST_TEMPLATE.md

packages/tsconfig/base.json
- enable ts noUncheckedIndexedAccess in base config
=> chore: enable ts noUncheckedIndexedAccess

.github/workflows/quality.yml, package.json, turbo.json
- add github action for quality checks: it will lint & test every packages / apps
I did not configure turbo cache here.
=> chore: add quality github action

template/.env.test, template/package.json, template/vitest.config.js
- set default vitest environment to `edge-runtime`
- load vitest env. variables from `.env.ts`
- add support for alias `@/`
=> chore(template): update vitest configuration

packages/elba-msw/.eslintrc.json, packages/elba-msw/README.md, packages/elba-msw/package.json, packages/elba-msw/src/auth-request-handler.ts, packages/elba-msw/src/index.ts, packages/elba-msw/src/request-handlers.ts, packages/elba-msw/src/resources/authentication.ts, packages/elba-msw/src/resources/connection-status.ts, packages/elba-msw/src/resources/data-protection.ts, packages/elba-msw/src/resources/third-party-apps.ts, packages/elba-msw/src/resources/users.ts, packages/elba-msw/tsconfig.json, packages/elba-schema/.eslintrc.json, packages/elba-schema/README.md, packages/elba-schema/package.json, packages/elba-schema/src/authentication.ts, packages/elba-schema/src/common.ts, packages/elba-schema/src/connection-status.ts, packages/elba-schema/src/data-protection.ts, packages/elba-schema/src/index.ts, packages/elba-schema/src/third-party-apps.ts, packages/elba-schema/src/users.ts, packages/elba-schema/tsconfig.json, pnpm-lock.yaml
- add package elba-msw
Can be used by each integration tests env to simulate elba Open API endpoints. It's using Zod to validate request payload.
=> chore: add elba-msw package

CONTRIBUTING.MD, README.md, template/README.md
- update the main readme to get ride of the default one added by turbo
- update the template readme to includes details about package scripts
N/A
=> docs: update template and main readme

.husky/pre-commit, package.json, packages/api-client/package.json, packages/schemas/package.json, packages/sdk/package.json, packages/test-utils/package.json, pnpm-lock.yaml
- add husky pre-commit that lint everything and check that commit don't happens on staging branch
- fix lint commands of packages
N/A
=> chore: add husky pre commit hook

packages/tsconfig/base.json, packages/utils/.eslintrc.json, packages/utils/README.md, packages/utils/package.json, packages/utils/src/crypto.test.ts, packages/utils/src/crypto.ts, packages/utils/src/index.ts, packages/utils/tsconfig.json, packages/utils/vitest.config.js, pnpm-lock.yaml
This adds a utils package that contains a collection of utils. For now it only contains crypto utils.
=> chore: add utils package

packages/utils/README.md
Update incorrect crypto instruction in utils package readme
=> fix(docs): update crypto instruction in utils package readme

packages/utils/src/crypto.ts
This fixes a bug where the crypto utils was throwing an error in edge runtime context
=> fix: crypto utils in edge runtime context

apps/github/src/app/install/route.ts, apps/github/src/app/setup/route.ts, packages/sdk/src/request-sender.ts, packages/test-utils/src/msw/auth-request-handler.ts
- add missing source_id search params in elba redirect url
- remove authorization header from sdk request
Sending a wrong bearer, make Hasura reject the request...
=> fix(github): missing source_id in elba redirect url

README.md, docs/architecture.md
- add architecture documentation
N/A
=> docs: add architecture documentation

README.md
- fix doc architecture broken link in readme.md
n/a
=> docs: fix readme doc architecture link

packages/sdk/README.md
- remove generated statement template in sdk's readme
n/a
=> docs(sdk): remove readme unnecessary statement

apps/dropbox/src/app/api/inngest/functions/data-protection/delete-object-permissions.ts, apps/dropbox/src/app/api/inngest/functions/data-protection/index.ts, apps/dropbox/src/app/api/inngest/functions/data-protection/refresh-object.test.ts, apps/dropbox/src/app/api/inngest/functions/data-protection/refresh-object.ts, apps/dropbox/src/app/api/inngest/functions/data-protection/synchronize-folders-and-files.test.ts, apps/dropbox/src/app/api/oauth/callback/service.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/delete-object-permissions/route.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.test.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/refresh-object/route.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/refresh-object/service.test.ts, apps/dropbox/src/app/api/webhooks/elba/data-protection/refresh-object/service.ts, apps/dropbox/src/common/__mocks__/elba.ts, apps/dropbox/src/common/clients/types.ts, apps/dropbox/src/repositories/dropbox/clients/dbx-files.ts, apps/dropbox/src/repositories/dropbox/clients/dbx-permissions.ts, apps/dropbox/src/repositories/dropbox/types/types.ts, apps/dropbox/vitest/setup-test-server.ts
=> feat(dropbox-dp-remove-permissions): remove file, folder permission & shared link

packages/schemas/src/data-protection.ts, packages/schemas/src/third-party-apps.ts, packages/sdk/src/webhooks/event-data.ts
Include data protection delete object permissions webhook validator
=> chore: add webhook validator for data protection delete object permissions

docs/api/connection-status/update-status.md, docs/api/data-protection/delete-objects.md, docs/api/data-protection/update-object.md, docs/api/data-protection/update-objects.md, docs/api/third-party-apps/delete-objects.md, docs/api/third-party-apps/update-objects.md, docs/api/users/delete-users.md, docs/api/users/update-users.md, docs/introduction.md
This PR contains the documents for the following apis
=> docs(api): elba API documents 

apps/dropbox/src/common/utils.ts, apps/dropbox/src/env.ts, apps/github/src/app/install/route.ts, apps/github/src/app/setup/route.ts, apps/github/src/env.ts, apps/microsoft/src/env.ts, apps/slack/src/app/install/route.ts, apps/slack/src/app/oauth/route.ts, packages/sdk/README.md, packages/sdk/src/utils/redirection.test.ts, packages/sdk/src/utils/redirection.ts, template/src/app/auth/route.ts
- add region support in install redirection url
This is a dirty fix and each integration should be refactored.
=> fix: install redirection url does not contains region

.github/workflows/quality.yml
- enable turbo cache on github workflows
N/a
=> chore: enable turbo cache on github workflows

apps/github/src/inngest/functions/index.ts
- add missing `removeOrganisation` inngest function export
N/A
=> fix(github): add inngest function removeOrganisation export

apps/microsoft/src/app/auth/service.test.ts, apps/microsoft/src/app/auth/service.ts
- reorder auth inngest batched events
It could fix the issue on staging / production. 
=> fix(microsoft): attempt to fix auth inngest batch events

apps/microsoft/src/inngest/client.ts
- add missing inngest unauthorized middleware
n/a
=> fix(microsoft): missing inngest unauthorized middleware

apps/dropbox/src/app/oauth/route.test.ts, apps/dropbox/src/app/oauth/service.ts, apps/dropbox/src/inngest/functions/organisations/remove-organisation.ts, apps/dropbox/src/inngest/functions/third-party-apps/sync-apps.ts, apps/dropbox/src/inngest/functions/tokens/refresh-token.test.ts, apps/dropbox/src/inngest/functions/tokens/refresh-token.ts, apps/dropbox/src/inngest/types.ts, packages/test-utils/src/inngest/function-mock.ts
fix cancel refresh token on multiple app install request
=> fix(dbx-token-refresh): fix cancel refresh token on multiple app install request

apps/dropbox/src/inngest/functions/data-protection/delete-object-permissions.ts, apps/dropbox/src/inngest/functions/data-protection/sync-folders-and-files.ts
=> chore: add prefix for events

apps/dropbox/package.json, apps/dropbox/src/inngest/functions/data-protection/start-folders-and-files-sync.ts, apps/dropbox/src/inngest/functions/data-protection/start-shared-links-sync.ts
=> chore: event name update

packages/schemas/src/users.ts, packages/sdk/src/webhooks/event-data.ts
- add delete user webhook data schema
N/A
=> feat: add delete user webhook data schema

apps/microsoft/src/common/crypto.ts
- add log to microsoft decryptText
N/A
=> chore(microsoft): add log to decrypt function

apps/microsoft/package.json, apps/microsoft/src/database/client.ts, apps/microsoft/src/inngest/functions/token/refresh-token.test.ts, apps/microsoft/src/inngest/functions/token/refresh-token.ts, pnpm-lock.yaml
- use db http fetch connection for production
- increase token refresh rate (refresh 30min before expiration)
N/A
=> fix(microsoft): db connection may not complete

apps/microsoft/package.json, apps/microsoft/src/database/client.ts, pnpm-lock.yaml
- remove db abort signal
- bump drizzle-orm version
N/A
=> fix(microsoft): remove db abort signal

apps/dropbox/src/connectors/dropbox/dbx-files.ts, apps/dropbox/src/connectors/utils/format-file-and-folders-to-elba.ts, apps/dropbox/src/connectors/utils/format-shared-links.ts, apps/dropbox/src/connectors/utils/helpers.ts, apps/dropbox/src/env.ts, apps/microsoft/package.json, apps/microsoft/src/database/client.ts, pnpm-lock.yaml
At the moment we are getting the file's metadata individually & this behaviour is cause for request too many request issue , in this PR the fetch metadata method changed to batchwise, therefore very few requests will be mad to fetch files metadata.
Before you create this PR, confirm all the requirements listed below by checking the …
=> chore: get files metadata batchwise (#195)

.husky/pre-commit, package.json, pnpm-lock.yaml, turbo.json
Rebase branch staging into main
=> rebase branch staging into main

.github/workflows/quality.yml, apps/dropbox/package.json, package.json
Update node version from 18 to 20
N/A
=> chore: update to node 20

apps/dropbox/src/common/crypto.ts, apps/microsoft/src/common/crypto.ts, apps/slack/src/common/crypto.ts, packages/inngest/src/middlewares/crypto.ts, packages/utils/README.md, packages/utils/src/crypto.test.ts, packages/utils/src/crypto.ts, template/src/common/crypto.ts
This updates the crypto utils to support specifying an IV when encrypting data
N/A
=> feat(crypto): support specifying IV

apps/teams/drizzle/0000_lowly_monster_badoon.sql, apps/teams/drizzle/meta/0000_snapshot.json, apps/teams/drizzle/meta/_journal.json, apps/teams/package.json, apps/teams/src/app/api/webhooks/microsoft/event-handler/route.ts, apps/teams/src/app/api/webhooks/microsoft/event-handler/types.ts, apps/teams/src/app/api/webhooks/microsoft/lifecycle-notifications/route.ts, apps/teams/src/app/api/webhooks/microsoft/lifecycle-notifications/types.ts
Fix pipeline by using correct NextJs route signatures and adding missed drizzle files migration files
=> fix: use correct NextJs route signatures

apps/teams/package.json, apps/teams/src/app/auth/service.test.ts, apps/teams/src/common/crypto.ts, apps/teams/src/inngest/functions/tokens/refresh-token.test.ts
Use correct crypto signatures and update few tests for refresh token flow.
=> fix(teams): use correct crypto signatures

apps/dropbox/package.json
Temporarily disable dropbox tests
=> chore(dropbox): temporarily disable dropbox tests

.github/workflows/quality.yml, apps/confluence/package.json, apps/dropbox/package.json, apps/github/package.json, apps/google/package.json, apps/microsoft/package.json, apps/slack/package.json, apps/teams/package.json, package.json, packages/api-client/package.json, packages/design-system/package.json, packages/inngest/package.json, packages/logger/package.json, packages/nextjs/package.json, packages/schemas/package.json, packages/sdk/package.json, packages/test-utils/package.json, packages/utils/package.json, pnpm-lock.yaml, template/package.json, turbo.json
This adds a script to type check apps and packages.
=> chore: add type checking script

apps/google/src/connectors/elba/users.ts, apps/google/src/connectors/google/users.ts
This adds logs and make `name` field optional to try to fix an error while parsing Google user 
=> fix(google): log and attempt to fix error while parsing user

apps/confluence/src/connectors/confluence/common/pagination.ts
- fix compute of next page on V1 api
N/A
=> fix(confluence): v1 api next page compute

apps/microsoft/src/connectors/microsoft/users.ts
- add filter on microsoft users listing request
N/A
=> refactor(microsoft): add filter on list users

packages/design-system/src/Select.tsx, packages/design-system/src/index.ts
- add Select component
The component is client side only because of the "need" to match elba's ui: the placeholder color is lighter than the selectable values color.
=> feat(design-system): add Select component

apps/teams/src/inngest/middlewares/rate-limit-middleware.test.ts, apps/teams/src/inngest/middlewares/rate-limit-middleware.ts
- add min rate limit delay of 15 minutes
While respecting Microsoft returned Rate-Limit value (60s) we continue to reach rate-limit again and again.
=> refactor(teams): add min rate limit delay

apps/google/src/inngest/client.ts
This temporarily disables inngest unauthorized to prevent false positives
=> fix(google): temporarily disable unauthorized middleware

apps/microsoft/src/connectors/microsoft/apps.ts, apps/microsoft/src/connectors/microsoft/users.ts
- add logs to connectors failed request's response
N/A
=> chore(microsoft): add connectors logs

apps/box/src/inngest/functions/users/synchronize-users.ts, apps/fivetran/src/inngest/functions/users/sync-users.ts, apps/microsoft/src/inngest/functions/third-party-apps/get-app-oauth-grants.ts, apps/microsoft/src/inngest/functions/third-party-apps/refresh-app-permission.ts, apps/microsoft/src/inngest/functions/third-party-apps/revoke-app-permission.ts, apps/microsoft/src/inngest/functions/third-party-apps/sync-apps.ts
- fix microsoft, fivetran and box inngest function priority config
N/A.
=> fix: bad inngest concurrency config

package.json, pnpm-lock.yaml
This overrides dependencies version to fix vulnerabilities
=> chore: update dependencies to fix vulnerabilities

apps/teams/package.json, apps/teams/src/app/auth/actions.ts, apps/teams/src/app/auth/layout.tsx, apps/teams/src/app/auth/page.tsx, apps/teams/src/app/auth/service.ts, pnpm-lock.yaml
=> fix(teams): fix build

apps/sharepoint/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.test.ts, apps/sharepoint/src/inngest/functions/data-protection/delete-item-permissions.test.ts
test update
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have added tests to cover the new feature or fixes.
=> feat(sharepoint): test updates

apps/aircall/src/inngest/functions/users/sync-users.test.ts, apps/aircall/src/inngest/functions/users/sync-users.ts, apps/asana/src/inngest/functions/users/sync-users.test.ts, apps/asana/src/inngest/functions/users/sync-users.ts, apps/box/src/inngest/functions/users/synchronize-users.test.ts, apps/box/src/inngest/functions/users/synchronize-users.ts, apps/calendly/src/inngest/functions/users/sync-users.test.ts, apps/calendly/src/inngest/functions/users/sync-users.ts, apps/datadog/src/inngest/functions/users/sync-users.test.ts, apps/datadog/src/inngest/functions/users/sync-users.ts, apps/fivetran/src/inngest/functions/users/sync-users.test.ts, apps/fivetran/src/inngest/functions/users/sync-users.ts, apps/jira/src/inngest/functions/users/sync-users.test.ts, apps/jira/src/inngest/functions/users/sync-users.ts, apps/linear/src/inngest/functions/users/sync-users.test.ts, apps/linear/src/inngest/functions/users/sync-users.ts, apps/segment/src/inngest/functions/users/sync-users.test.ts, apps/segment/src/inngest/functions/users/sync-users.ts, apps/zoom/src/inngest/functions/users/sync-users.test.ts, apps/zoom/src/inngest/functions/users/sync-users.ts
`isSuspendable ` flag added to all the integrations that support user deletion
=> chore: include isSuspendable flag to sync user object

apps/google/src/inngest/functions/data-protection/sync-personal-drives.test.ts, apps/google/src/inngest/functions/data-protection/sync-personal-drives.ts, apps/google/src/inngest/functions/data-protection/sync-shared-drives.test.ts, apps/google/src/inngest/functions/data-protection/sync-shared-drives.ts, apps/google/src/inngest/functions/data-protection/sync.test.ts, apps/google/src/inngest/functions/data-protection/sync.ts
This increases the inngest waitForEvent timeout from 1 day to 30 days
=> chore(google): set inngest waitForEvent timeout to 30 days

apps/aircall/package.json, apps/asana/package.json, apps/box/package.json, apps/calendly/package.json, apps/confluence/package.json, apps/datadog/package.json, apps/dbtlabs/package.json, apps/doppler/package.json, apps/dropbox/package.json, apps/fivetran/package.json, apps/github/package.json, apps/google/package.json, apps/intercom/package.json, apps/jira/package.json, apps/linear/package.json, apps/microsoft/package.json, apps/notion/package.json, apps/openai/package.json, apps/segment/package.json, apps/sharepoint/package.json, apps/slack/package.json, apps/teams/package.json, apps/yousign/package.json, apps/zoom/package.json, packages/inngest/package.json, packages/test-utils/package.json, packages/test-utils/src/inngest/function-mock.ts, pnpm-lock.yaml, template/package.json
This improves the inngest test utils:
- supports batch events
- return `ids` when using `waitForEvent`
=> chore: improve inngest test utils

apps/sharepoint/src/inngest/functions/data-protection/sync-drives.ts, apps/sharepoint/src/inngest/functions/data-protection/sync-items.ts, apps/sharepoint/src/inngest/functions/data-protection/sync-sites.ts, apps/sharepoint/src/inngest/functions/delta/initialize-delta.ts, apps/sharepoint/src/inngest/functions/subscriptions/create-subscription.ts, apps/sharepoint/src/inngest/functions/users/sync-users.ts
This branch was used to "hotfix" jobs in production as new job were scheduled by scheduler. I made changes to early return non first sync jobs.
Since, I reverted the changes, updated the cron scheduler to schedule less often.
What's left is a change to remove non properly working priority job during the sync.
=> fix(sharepoint): fix priority

apps/zoom/src/connectors/zoom/users.test.ts, apps/zoom/src/connectors/zoom/users.ts, apps/zoom/src/inngest/functions/users/sync-users.test.ts, apps/zoom/src/inngest/functions/users/sync-users.ts
Zoom Integration
1. Added `isSuspendable` and `url` params
2. Can't deactivate a user with a role of `owner` and `admin`.
N/A
=> feat(zoom): add isSuspendable and url params

apps/calendly/drizzle/0001_lame_fixer.sql, apps/calendly/drizzle/meta/0001_snapshot.json, apps/calendly/drizzle/meta/_journal.json, apps/calendly/src/app/auth/service.test.ts, apps/calendly/src/app/auth/service.ts, apps/calendly/src/connectors/calendly/auth.test.ts, apps/calendly/src/connectors/calendly/users.test.ts, apps/calendly/src/connectors/calendly/users.ts, apps/calendly/src/database/schema.ts, apps/calendly/src/inngest/functions/organisations/remove-organisation.test.ts, apps/calendly/src/inngest/functions/token/refresh-token.test.ts, apps/calendly/src/inngest/functions/users/delete-users.test.ts, apps/calendly/src/inngest/functions/users/schedule-users-sync.test.ts, apps/calendly/src/inngest/functions/users/sync-users.test.ts, apps/calendly/src/inngest/functions/users/sync-users.ts
=> feat(calendly): add isSuspendable and url params, authUserUri.

apps/datadog/drizzle/0001_secret_kid_colt.sql, apps/datadog/drizzle/meta/0001_snapshot.json, apps/datadog/drizzle/meta/_journal.json, apps/datadog/src/app/install/actions.tsx, apps/datadog/src/app/install/service.test.ts, apps/datadog/src/app/install/service.ts, apps/datadog/src/connectors/datadog/regions.ts, apps/datadog/src/connectors/datadog/users.test.ts, apps/datadog/src/connectors/datadog/users.ts, apps/datadog/src/database/schema.ts, apps/datadog/src/inngest/functions/organisations/remove-organisation.test.ts, apps/datadog/src/inngest/functions/users/delete-user.test.ts, apps/datadog/src/inngest/functions/users/schedule-users-sync.test.ts, apps/datadog/src/inngest/functions/users/sync-users.test.ts, apps/datadog/src/inngest/functions/users/sync-users.ts, apps/datadog/src/inngest/middlewares/unauthorized-middleware.test.ts
Datadog Integration
1. Added `url` params, not `isSuspendable` because I couldn't filter owner and its id.
2. Modified user deletion to suspension.
N/A
=> feat(datadog): add url param, modify user deletion to suspension (#400)

apps/datadog/src/connectors/datadog/users.test.ts, apps/datadog/src/connectors/datadog/users.ts, apps/datadog/src/inngest/functions/users/sync-users.test.ts
filter users by service account
=> chore(datadog): ignore service account during users sync

apps/jira/drizzle/0001_dry_omega_red.sql, apps/jira/drizzle/meta/0001_snapshot.json, apps/jira/drizzle/meta/_journal.json, apps/jira/src/app/install/service.test.ts, apps/jira/src/app/install/service.ts, apps/jira/src/connectors/jira/users.ts, apps/jira/src/database/schema.ts, apps/jira/src/inngest/functions/organisations/remove-organisation.test.ts, apps/jira/src/inngest/functions/users/delete-user.test.ts, apps/jira/src/inngest/functions/users/schedule-users-sync.test.ts, apps/jira/src/inngest/functions/users/sync-users.test.ts, apps/jira/src/inngest/functions/users/sync-users.ts, apps/jira/src/inngest/middlewares/unauthorized-middleware.test.ts
Add isSuspendable and url params
=> chore(jira): add isSuspendable and url params

apps/jira/src/app/install/actions.tsx
handle wrong domain name error & Improve error message, 
=> chore: display correct error message when the given domain is invalid

apps/jira/src/app/install/actions.tsx
When the domain is expired, it returns 503 & it is handled in this PR
=> chore: handle, cloud subscription has been deactivated error

apps/15five/src/app/install/actions.tsx
Improve invalid token error handling
=> chore: handle 403 error on app registrations

apps/sentry/src/inngest/functions/index.ts, apps/sentry/src/inngest/functions/token/refresh-token.test.ts
Include missing sentry refresh token function
=> chore: include missing refresh token inngest function

apps/azuredevops/src/app/install/route.ts
Remove unnecessary scope request
=> chore: remove unnecessary scope request

pnpm-lock.yaml, pnpm-workspace.yaml
This updates the `inngest` & `inngest-cli` dependencies
=> chore: update inngest

packages/schemas/src/index.ts, packages/schemas/src/installation.ts, packages/sdk/src/webhooks/event-data.ts
This adds a new webhook to validate the installation.
=> feat: add webhook to validate installation

packages/test-utils/src/vitest/elba-sdk-spy.ts
This adds missing mock for the elba sdk organisation endpoint 
=> fix(sdk): add test mock for organisation endpoint

packages/api-client/src/routes/organisations.ts
This updates the organisation mock
=> chore: update list organisation mock

apps/calendly/src/app/api/webhooks/elba/installation/validate/service.ts, apps/docusign/src/app/api/webhooks/elba/installation/validate/service.ts, apps/linear/src/app/api/webhooks/elba/installation/validate/service.ts, apps/notion/src/app/api/webhooks/elba/installation/validate/service.ts, apps/zoom/src/app/api/webhooks/elba/installation/validate/service.ts
This adds missing error logs during installation validation
=> chore: add missing installation validation error logs

apps/slack/src/app/oauth/service.ts
This fixes Slack installation for the following cases:
- When an organisation was trying to install slack with a team that was already in database for a different organisation, the different organisation would still be tied to that team. Now the last organisation will be tied to that team.
- When an organisation was trying to install slack with a team that is different from the one it is tied to in database, the installation would just fail. Now the previous team tied to the organisation is removed from database before inserting the new one.
=> fix(slack): fix installation flow

apps/asana/src/app/api/inngest/route.ts
=> chore(asana): change region

packages/config/next/next.config.js
This speeds up the vercel deployments by skipping type checking and linting during build
=> chore: speed up vercel deployment

apps/sentry/src/inngest/functions/index.ts
This fixes Sentry token refresh due to missing function import
=> fix(sentry): token refresh

apps/teams/src/inngest/functions/organisations/remove-organisation.ts
This attempts to fix Teams organisation removal inngest and add debug log during inngest function execution
=> fix: attempt to fix Teams organisation removal

apps/github/src/inngest/client.ts, apps/slack/src/inngest/client.ts
This fixes missing logger in Slack & Github inngest clients. The logs were not properly formatted
=> fix: missing inngest logger

turbo/generators/config.ts
This fixes integration generator with command `pnpm generate` on windows
=> fix: integration generator on windows

CONTRIBUTING.md
This PR updates the contributing guidelines to implement a more efficient review process for template-based SaaS integrations. The changes help reviewers focus only on integration-specific code changes rather than the entire template-generated codebase.
=> docs: update contributing section

apps/gmail/package.json, apps/gmail/src/inngest/functions/gmail/list-messages.ts, pnpm-lock.yaml
=> chore(gmail): handle gmail API rate limit
