elba-security/elba-security

packages/eslint-config-custom/next.js
- force ts `type` keyword usage over `interface` (it currently the contrary)
- disable `unicorn/filename-case`
=> chore: eslint rules

packages/eslint-config-custom/next.js
- enable eslint unicorn filename case rule except for tsx file
- fix `@typescript-eslint/consistent-type-definitions`
I have previously disabled this rule because it was annoying for `tsx` file. But it turn out that it possible to disable it for `tsx` files.
This fix the lint script on every apps (+ template).
=> chore: enable unicorn-filename-case

packages/elba-api/.eslintrc.json, packages/elba-api/.gitignore, packages/elba-api/README.md, packages/elba-api/package.json, packages/elba-api/server.ts, packages/elba-api/src/index.ts, packages/elba-api/src/routes/authentication.ts, packages/elba-api/src/routes/connection-status.ts, packages/elba-api/src/routes/data-protection.ts, packages/elba-api/src/routes/index.ts, packages/elba-api/src/routes/third-party-apps.ts, packages/elba-api/src/routes/users.ts, packages/elba-api/src/utils.ts, packages/elba-api/tsconfig.json, packages/elba-msw/package.json, packages/elba-msw/src/resources/authentication.ts, packages/elba-msw/src/resources/connection-status.ts, packages/elba-msw/src/resources/data-protection.ts, packages/elba-msw/src/resources/third-party-apps.ts, packages/elba-msw/src/resources/users.ts, packages/tsconfig/base.json, pnpm-lock.yaml
This adds the `elba-api` package.
This package contains a minimal http server to run a mocked elba api locally.
The package is also the source of truth regarding the elba api routes, now the `elba-msw` packages import the routes request handler directly from it instead of defining them. 
=> chore: add elba-api package

template/package.json
- fix neondatabse version in template
This fix an issue introduced in version `0.6.1`. Note that version `0.7` is probably not supported by the vercel connector.
=> chore: fix neondatabase version

packages/sdk/src/webhooks/request-signature.test.ts, packages/sdk/src/webhooks/request-signature.ts
This fixes a bug where validating elba signature was not working due to the fact it was trying to JSON stringify a string, adding unecessary quotes wrapping the string and failing to verify correctly that the signatures were matching.
=> fix: elba signature verification

apps/slack/src/inngest/functions/slack/event-handlers/channel-shared.test.ts
- fix slack test not passing due to db order mismatch
This test was randomly failing because the db does not guaranty to returns result in a certains order.
=> fix(slack): test not passing due to db order mismatch

packages/api-client/package.json, packages/api-client/server.ts, pnpm-lock.yaml
- add `-v` argument to `start` script that enable verbose mode
- when verbose mode is on every request bodies are logged
N/A
=> feat(api-client): add verbose mode

apps/slack/src/common/env.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversation-messages.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversation-thread-messages.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversations.ts
- add inngest conversation functions config env variables
- bump team function concurrency from 3 to 10
Here are the env variables:
```
SLACK_SYNC_CONVERSATIONS_RETRY
SLACK_SYNC_CONVERSATIONS_MESSAGES_CONCURRENCY
SLACK_SYNC_CONVERSATIONS_MESSAGES_RETRY
SLACK_SYNC_CONVERSATIONS_THREAD_MESSAGES_CONCURRENCY
SLACK_SYNC_CONVERSATIONS_THREAD_MESSAGES_RETRY
```
=> feat(slack): add inngest conversation functions config env variables

apps/microsoft/src/app/auth/service.test.ts, apps/microsoft/src/app/auth/service.ts, apps/microsoft/src/inngest/functions/token/refresh-token.test.ts, apps/microsoft/src/inngest/functions/token/refresh-token.ts
- fix wrong refresh token timing
`expires_at` is in seconds, not minutes.
=> fix(microsoft): wrong refresh token timing

apps/dropbox/src/app/api/webhooks/elba/third-party-apps/start-sync/service.test.ts, apps/dropbox/src/app/api/webhooks/elba/third-party-apps/start-sync/service.ts, apps/dropbox/src/app/oauth/route.test.ts, apps/dropbox/src/app/oauth/service.ts, apps/dropbox/src/inngest/functions/third-party-apps/schedule-apps-sync.test.ts, apps/dropbox/src/inngest/functions/third-party-apps/schedule-apps-sync.ts, apps/dropbox/src/inngest/functions/third-party-apps/sync-apps.test.ts, apps/dropbox/src/inngest/functions/third-party-apps/sync-apps.ts, apps/dropbox/src/inngest/functions/tokens/refresh-token.test.ts, apps/dropbox/src/inngest/functions/tokens/refresh-token.ts, apps/dropbox/src/inngest/functions/users/schedule-user-sync.test.ts, apps/dropbox/src/inngest/functions/users/schedule-user-sync.ts, apps/dropbox/src/inngest/functions/users/sync-user-page.test.ts, apps/dropbox/src/inngest/functions/users/sync-user-page.ts, apps/dropbox/src/inngest/types.ts, apps/microsoft/src/app/auth/service.test.ts, apps/microsoft/src/app/auth/service.ts, apps/microsoft/src/inngest/client.ts, apps/microsoft/src/inngest/functions/token/refresh-token.test.ts, apps/microsoft/src/inngest/functions/token/refresh-token.ts, apps/microsoft/src/inngest/functions/users/schedule-users-syncs.test.ts, apps/microsoft/src/inngest/functions/users/schedule-users-syncs.ts, apps/microsoft/src/inngest/functions/users/sync-users.test.ts, apps/microsoft/src/inngest/functions/users/sync-users.ts, docs/recipes/refreshing-token.md
- rename event name suffix from .triggered to .requested
It was previously a mix without a any good reason (`requested` had more occurences then `triggered`) 
=> refactor: rename event name suffix to .requested

apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/route.ts, apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/service.ts
This adds logs to the `fetch-data-protection-object-content` endpoint to troubleshoot issues
=> chore: add some logs to troubleshoot slack endpoint to fetch data protection object content

template/vercel.json
This increases the serverless function maximum execution time to 60 seconds. Currently the default serverless function maximum execution time is 15 seconds, [see vercel blogpost here](https://vercel.com/changelog/serverless-functions-can-now-run-up-to-5-minutes).
It should avoid timeouts of time consuming inngest steps / functions.
For now only the `/api` path is affected.
=> chore: set serverless function maximum execution time to 60 seconds

apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/service.test.ts, apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/service.ts
This updates the fetch data protection object content webhook to return an empty content when hitting rate limit to avoid spamming the Slack API 
=> fix(slack): return empty content when fetch data protection object content webhook hit rate limit

apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/service.test.ts, apps/slack/src/app/api/webhook/elba/fetch-data-protection-object-content/service.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversation-messages.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversation-thread-messages.ts, apps/slack/src/inngest/functions/conversations/synchronize-conversations.ts, apps/slack/src/inngest/functions/users/synchronize-users.ts
Use inngest onFailure on data protection sync to avoid having stuck syncs when an error occurs.
This also add steps to avoid doing multiple request to elba for example as it can be executed multiple times if steps are following. It should also improve debugging experience.
=> fix(slack): use onFailure inngest option to avoid having stuck sync

apps/dropbox/src/connectors/dropbox/dbx-files.ts, apps/dropbox/src/connectors/utils/format-file-and-folders-to-elba.ts, apps/dropbox/src/connectors/utils/format-shared-links.ts, apps/dropbox/src/connectors/utils/helpers.ts, apps/dropbox/src/env.ts
At the moment we are getting the file's metadata individually & this behaviour is cause for request too many request issue , in this PR the fetch metadata method changed to batchwise, therefore very few requests will be mad to fetch files metadata.
=> chore: get files metadata batchwise

packages/test-utils/src/vitest/setup-database.ts
This fixes an error where too many open connections postgres error could be encountered while running tests
N/A
=> fix: too many open connections postgres error when running tests

apps/google/src/connectors/google/clients.ts
This fixes a bug where Google server wouldn't be able to handle some request sometimes, leading to triggering false Google unauthorized error which by consequence would remove the organisation and set a source connection error.
For now we verify that the status code is a 401 to remove this false positive, Google returning a 400 when unable to handle requests.
=> fix(Google): check 401 response status when verifying DWD scopes

packages/design-system/global.d.ts, packages/design-system/src/index.ts, packages/design-system/tsconfig.json
This fixes a bug where integration couldn't be built because reference to react-dom canary wasn't properly imported
=> fix(design-system): update react dom canary types reference

apps/google/src/connectors/google/files.ts, apps/google/src/inngest/functions/data-protection/refresh-object.test.ts, apps/google/src/inngest/functions/data-protection/refresh-object.ts, packages/test-utils/src/inngest/function-mock.ts
This fixes an issue where deleted Google Drive files were not properly handled while refreshing an issue. This is because Inngest is wrapping errors from step with `StepError`. A solution would be to get the `cause` but Inngest StepError is not setting `cause` attribute: https://github.com/inngest/inngest-js/blob/28a8750239a68815d9c4ada32e0df1b434bf66de/packages/inngest/src/components/StepError.ts#L12
I also updated our mock inngest function util to throw StepError to avoid this error as well in our tests
=> fix(Google): fix a bug where refreshing a deleted Google drive file was not properly handled

apps/confluence/src/connectors/elba/data-protection/objects.ts, apps/confluence/src/inngest/functions/__mocks__/confluence-pages.ts, apps/confluence/src/inngest/functions/__mocks__/confluence-spaces.ts, apps/confluence/src/inngest/functions/__mocks__/organisations.ts, apps/confluence/src/inngest/functions/data-protection/schedule-data-protection-syncs.test.ts, apps/confluence/src/inngest/functions/users/schedule-users-syncs.test.ts
confluence API changed and remove /wiki from objects url
- add `/wiki` in the data protection object url 
N/A
=> refactor(confluence): update objects url

apps/github/src/connectors/github/app.test.ts, apps/github/src/connectors/github/app.ts, apps/github/src/connectors/github/organization.test.ts, apps/github/src/connectors/github/organization.ts, apps/github/src/inngest/functions/third-party-apps/__mocks__/github.ts, apps/github/src/inngest/functions/third-party-apps/sync-apps-page.ts
- use installation url as app url
Because sent apps to elba are unique to each installation this url will be unique for each organisation installation.
It redirect directly to the settings page of the app installation letting the admin uninstall the app.
=> fix(github): fix github app settings url

apps/sharepoint/src/connectors/microsoft/sharepoint/permissions.test.ts, apps/sharepoint/src/connectors/microsoft/sharepoint/permissions.ts, apps/sharepoint/src/inngest/client.ts, apps/sharepoint/src/inngest/functions/data-protection/common/helpers.ts, apps/sharepoint/src/inngest/functions/data-protection/common/types.ts, apps/sharepoint/src/inngest/functions/data-protection/delete-item-permissions.test.ts, apps/sharepoint/src/inngest/functions/data-protection/delete-item-permissions.ts, apps/sharepoint/src/inngest/functions/data-protection/refresh-item.test.ts, apps/sharepoint/src/inngest/functions/data-protection/sync-items.test.ts, apps/sharepoint/src/inngest/functions/data-protection/update-items.test.ts
Sync Item logic update, now permissions combined to one user-permissions instance, also delete item permissions logic updated.
=> feat(sharepoint): sync and delete item permissions update

packages/eslint-config-custom/library.js, packages/eslint-config-custom/next.js
This fixes an eslint issue while trying to lint non typescript files
=> fix: eslint config

apps/slack/.env.test, apps/slack/src/common/env.ts, apps/slack/src/inngest/functions/data-protection/schedule-data-protection-sync.ts
Slack data protection sync frequency was hardcoded and is now set using environment variable
=> chore(slack): set data protection sync schedule frequency from environment variable

apps/google/src/connectors/google/permissions.ts, apps/google/src/inngest/functions/data-protection/sync-drive.test.ts, apps/google/src/inngest/functions/data-protection/sync-drive.ts, apps/google/src/inngest/functions/data-protection/sync-shared-drives.test.ts, apps/google/src/inngest/functions/data-protection/sync-shared-drives.ts
This fixes a bug where permissions deletion would be ignored for files on shared drives.
The parameter `supportsAllDrives` was not set during the api call to delete permission. As a consequence, the response was 404 `notFound` which we just ignored assuming the permission was already deleted while it was not.
This also updates the logic to list list files on personal drives to make sure the file is owned by the owner of the personal drive. Instead of relying on email, which could change and might not be reliable, we are now using the user id instead.
=> fix(Google): fix shared drive files permissions deletion

.github/workflows/quality.yml, apps/google/src/inngest/functions/data-protection/sync-drive.test.ts, apps/google/src/inngest/functions/data-protection/sync-drive.ts
This fixes a bug where personal drive files would be ignored during sync due to a [bug](https://github.com/elba-security/elba-security/blob/2b4016956383790fd0e7e2435bea11ad5ee6327c/apps/google/src/inngest/functions/data-protection/sync-drive.ts#L84) where we attempted to use user id instead of user email to only keep files owned by the owner of the personal drive
Now instead of relying on email or user id, we can rely on property `me` in `owners` property
=> fix(Google): fix a bug during personal drive

apps/google/src/inngest/functions/data-protection/sync-personal-drives.ts, apps/google/src/inngest/functions/data-protection/sync-shared-drives.ts, apps/google/src/inngest/functions/data-protection/sync.ts, apps/sharepoint/src/inngest/functions/data-protection/sync-drives.ts, apps/sharepoint/src/inngest/functions/data-protection/sync-sites.ts, apps/sharepoint/src/inngest/functions/organisations/remove-organisation.ts, apps/teams/src/inngest/functions/channels/sync-channels.ts, apps/teams/src/inngest/functions/channels/sync-messages.ts, apps/teams/src/inngest/functions/channels/sync-teams.ts
This is a recommendation from Inngest team which might resolve some issues that could occur sometimes. Instead of using a hack to first creating an array of promises using `waitForEvent` and then use `sendEvent` and finally await for the array of promises, they suggested to use `Promise.all()` with both the array of `waitForEvent` & `sendEvent`. There shouldn't be any race, the backend would receive the `waitForEvent` & `sendEvent` and would handle `waitForEvent` first. 
=> fix: trigger and await waitForEvent & sendEvent at the same time

apps/datadog/src/connectors/datadog/regions.ts, apps/datadog/src/connectors/datadog/users.test.ts, apps/datadog/src/connectors/datadog/users.ts, apps/datadog/src/inngest/functions/users/sync-users.test.ts, apps/datadog/src/inngest/functions/users/sync-users.ts
Datadog Integration
1. Added `url` params, not `isSuspendable` because I couldn't filter owner and its id.
2. Modified user deletion to suspension.
N/A
=> feat(datadog): add url param, modify user deletion to suspension

packages/api-client/package.json, pnpm-lock.yaml
Inngest use hono behind the hood, but a different version that was installed by `api-client`. Pnpm was locking two version of inngest and resolving the bad one for apps. It's look like a pnpm bug. This PR should do the trick. Other fix could be to force resolution of hono in each apps package.json, but it's simpler to just downgrade our version of hono in `api-client`.
- fix inngest pnpm resolution
=> chore: fix inngest pnpm resolution

apps/zoom/src/connectors/zoom/auth.ts, apps/zoom/src/inngest/functions/token/refresh-token.ts
It return  error code 400 after few refresh,  it seems we are refreshing too early, therefore it is set to refresh before 10min, however I am not sure of the error, I suspect it could be related to this issue , https://devforum.zoom.us/t/cannot-renew-access-token-refresh-token-for-some-users-400-invalid-token/76400 , I added a log to debug 
=> chore:  increase the refresh token time interval

apps/jira/src/app/install/actions.tsx
Fix response body read error using response.clone()
Implemented response cloning to allow multiple reads of the response body
=> fix:  Implemented response cloning to allow multiple reads of the response body

apps/google/src/inngest/functions/data-protection/delete-object-permissions.ts
This increases the inngest concurrency to remove Google data protection objects permissions
=> feat(google): increase delete data protection object permissions concurrency

apps/confluence/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.test.ts, apps/onedrive/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.test.ts, apps/onedrive/src/app/api/webhooks/elba/data-protection/refresh-object/service.test.ts, apps/onedrive/src/app/api/webhooks/elba/data-protection/start-sync/service.test.ts, apps/sharepoint/src/app/api/webhooks/elba/data-protection/delete-object-permissions/service.test.ts, apps/sharepoint/src/app/api/webhooks/elba/data-protection/refresh-object/service.test.ts, apps/sharepoint/src/app/api/webhooks/elba/data-protection/start-sync/service.test.ts, packages/schemas/src/authentication.ts, packages/schemas/src/common.ts, packages/schemas/src/data-protection.ts, packages/schemas/src/third-party-apps.ts, packages/schemas/src/users.ts, packages/sdk/src/webhooks/event-data.test.ts, packages/sdk/src/webhooks/event-data.ts
This handle region & nango connection id in webhooks. The webhooks can no retrieve them using `region` & `nangoConnectionId`
=> feat: handle region & nango connection id in webhooks

apps/linear/src/connectors/linear/users.test.ts, apps/linear/src/connectors/linear/users.ts
We used  the following query to fetch the auth user 
`
query WhoAmI {
user(id: "me") {
id
}
}
`
but it is not the case here, therefore the query is adjusted to this
`
query Me {
viewer {
id
}
}
`
[Linear documentation to get the auth user.](https://developers.linear.app/docs/graphql/working-with-the-graphql-api#queries-mutations)
=> fix(linear): me id used to fetch the current auth user but it is not the case therefore viewer is used

packages/inngest/package.json, packages/inngest/src/middlewares/elba-connection-error.test.ts, packages/inngest/src/middlewares/elba-connection-error.ts, packages/inngest/src/middlewares/index.ts, pnpm-lock.yaml
This adds an elba connection error inngest middleware.
The purpose of this middleware is to detect serious errors thrown during an inngest function execution. When the error is considered severe enough, it will abort the function executions and retries with an inngest NonRetriableError, and will send the desired event to trigger the inngest integration function to set an elba connection error.
=> feat: add elba connection error inngest middleware

apps/onedrive/src/connectors/microsoft/delta/delta.test.ts, apps/onedrive/src/connectors/microsoft/delta/delta.ts, apps/onedrive/src/connectors/microsoft/users/users.test.ts, apps/onedrive/src/connectors/microsoft/users/users.ts, apps/onedrive/src/inngest/functions/data-protection/sync.test.ts, apps/onedrive/src/inngest/functions/data-protection/sync.ts
This fixes a bug where the `skipToken` provided by microsoft when listing users during data protection sync could expire if the sync was taking few hours for a single users page.
To fix this, instead of relying of the traditional endpoint to list users, we now rely on the delta users endpoint, where the token should in theory not expire.
=> fix(onedrive): fix expired token while listing users during data protection sync

apps/google/package.json, apps/google/src/connectors/google/permissions.ts, apps/google/src/inngest/functions/data-protection/delete-object-permissions.test.ts, apps/google/src/inngest/functions/data-protection/delete-object-permissions.ts, pnpm-lock.yaml
This use batch to delete Google permissions.
As the  official `googleapis` node library [doesn't support batch](https://github.com/googleapis/google-api-nodejs-client/issues/2375), 
the package `@jrmdayn/googleapis-batcher` has been added, allowing batch request through the usage of `fetchImplementation` option provided by `googleapis`.
=> chore(Google): batch delete permissions

apps/calendly/src/app/api/webhooks/elba/installation/validate/service.ts, apps/calendly/src/connectors/calendly/users.ts, apps/calendly/src/connectors/common/error.ts, apps/docusign/src/connectors/common/error.ts
Check if user is admin during Calendly installation validation
=> fix(calendly): check admin role during installation validation

apps/onedrive/src/inngest/functions/subscriptions/remove-subscription.ts, apps/sharepoint/src/inngest/functions/subscriptions/remove-subscription.ts, apps/teams/src/inngest/functions/organisations/remove-organisation.ts
This fixes a bug for some Microsoft integration that were trying to remove subscription during organisation removal. These subscriptions removal could fail which would result in not properly removing the organisation and setting its connection error
=> fix: organisation connection error

apps/microsoft/src/inngest/functions/token/refresh-token.ts, apps/onedrive/src/inngest/functions/organisations/remove-organisation.test.ts, apps/sharepoint/src/inngest/functions/organisations/remove-organisation.test.ts, apps/teams/src/inngest/client.ts, apps/teams/src/inngest/functions/channels/index.ts, apps/teams/src/inngest/functions/data-protection/index.ts, apps/teams/src/inngest/functions/organisations/index.ts, apps/teams/src/inngest/functions/organisations/remove-organisation.test.ts, apps/teams/src/inngest/functions/organisations/remove-organisation.ts, apps/teams/src/inngest/functions/subscriptions/index.ts, apps/teams/src/inngest/functions/subscriptions/remove-subscription.test.ts, apps/teams/src/inngest/functions/subscriptions/remove-subscription.ts, apps/teams/src/inngest/functions/teams/event-handlers/index.ts, apps/teams/src/inngest/functions/teams/index.ts, apps/teams/src/inngest/functions/tokens/index.ts
This fixes Microsoft integrations.
Changes:
- Microsoft integration: remove organisation properly when facing unauthorized error during token refresh
- Teams integration: fix organisation removal that was trying to remove every organisation subscription which could lead to too many requests. This has been fixed by having a dedicated inngest function to remove a subscription like on OneDrive & SharePoint integrations.
=> fix: microsoft integrations

apps/dropbox/src/connectors/elba/data-protection/files.ts, apps/dropbox/src/connectors/elba/data-protection/folders.ts, apps/dropbox/src/inngest/functions/data-protections/__mocks__/sync-folder-and-files.ts
In the early implementation `updatedAt` property wasn't sent to files,  in this PR it is added
=> chore(dropbox-updatedAt): include updatedAt property for files

apps/google/src/connectors/google/users.ts
This fixes Google users zod validation. Some users could have weirdly formatted additional email addresses like `*@domain.local` which would break zod validation.
Now the user is now properly parsed without exception ignoring these invalid emails 
=> fix(google): ignore invalid user emails

apps/google/src/connectors/google/files.ts, apps/google/src/inngest/functions/data-protection/sync-drive.test.ts, apps/google/src/inngest/functions/data-protection/sync-drive.ts
This improves Google data protection sync. We now use the `shared` file attribute to know if a file is shared or not. This attribute only works for personal drives. When the file is not shared, we avoid retrieving its permissions and sending it. By consequence, personal drives sync speed should be improved
Before you create this PR, confirm all the requirements listed below by
checking the checkboxes like this (`[x]`).
areas.
=> chore(google): personal drive sync optimization

apps/google/src/connectors/elba/data-protection.ts, apps/google/src/connectors/google/files.ts, apps/google/src/inngest/functions/data-protection/refresh-object.test.ts, apps/google/src/inngest/functions/data-protection/sync-drive.test.ts
This change introduces the ingestion of the `modifiedTime` field from the Google API into the `updatedAt` field of elba's data protection object.
The changes include:
-  Updating the Google file Zod schema to incorporate the `modifiedTime` field.
-  Requesting the `modifiedTime` field from Google's API.
-  Properly mapping the `modifiedTime` field from Google to Elba's `updatedAt` object.
This change is done to track the last time a file was updated by any user with permissions, allowing elba to take appropriate actions based on this data point.
Completes E-3207.
=> feat(google): ingest file last modified date from Google Drive

apps/gitlab/README.md, apps/gitlab/src/connectors/gitlab/users.test.ts, apps/gitlab/src/connectors/gitlab/users.ts
Complete rewrite of GitLab integration to properly match the official API documentation after thorough review.
- **User Schema**: Properly reflects actual GitLab API response fields
- Required fields: `id`, `username`, `name`, `state`, `locked`, `avatar_url`, `web_url`
- Admin-only fields: `email`, `created_at`, `is_admin` (only visible when requester is admin)
- Optional fields: `bot`, `external`
- **Problem**: The `is_admin` field is only present in the response when the user is actually an admin
- **Solution**: Made `is_admin` optional in schema and check for `\!== true` instead of falsy
- Added `active=true` and `blocked=false` query parameters
- Additional filtering for bot users (`bot: true`)
- Additional filtering for external users (`external: true`)
- Double-check state is …
=> fix: align GitLab integration with official API documentation

apps/onedrive/src/connectors/microsoft/delta/delta.test.ts, apps/onedrive/src/connectors/microsoft/delta/delta.ts, apps/sharepoint/src/connectors/microsoft/delta/delta.test.ts, apps/sharepoint/src/connectors/microsoft/delta/delta.ts
Ticket [E-3450](https://linear.app/elba/issue/E-3450/investigate-sharepoint-and-onedrive-integrations-errors)
We have plenty errors for both integrations (onedrive and sharepoint) in `getDeltaItems` function. According to logs we are receiving 410 from MS Graph, potentially it could be this issue - https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#response-2
> There may be cases when the service can't provide a list of changes for a given token (for example, if a client tries to reuse an old token after being disconnected for a long time, or if server state has changed and a new token is required). In these cases the service returns an HTTP 410 Gone error with an error response containing one of the error codes below, and a Location header …
=> feat(onedrive & sharepoint): add logs to getDeltaItems request [E-3450]

apps/gmail/src/inngest/functions/third-party-apps/analyze-email.test.ts, apps/gmail/src/inngest/functions/third-party-apps/analyze-email.ts, apps/gmail/src/inngest/functions/third-party-apps/sync-email.test.ts, apps/gmail/src/inngest/functions/third-party-apps/sync-email.ts, apps/gmail/src/inngest/functions/third-party-apps/sync-inbox.test.ts, apps/gmail/src/inngest/functions/third-party-apps/sync-inbox.ts, apps/gmail/src/inngest/functions/third-party-apps/sync.ts
This PR allows an onrganisation to be sync several time during a 24h window
- add to `analyzeEmail` rate-limit key date of start of sync
=> feat(gmail): allow an organisation to be sync several time a day
